# Generated by Django 6.0.2 on 2026-02-05 22:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_phone', models.IntegerField()),
                ('doctor_address', models.CharField(max_length=200)),
                ('doctor_willaya', models.CharField(max_length=50)),
                ('doctor_pic', models.BinaryField(blank=True, null=True)),
                ('doctor_cotas', models.IntegerField()),
                ('doctor_leftcotas', models.IntegerField()),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_willaya', models.CharField(max_length=50)),
                ('admin_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'leader',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_companyid', models.IntegerField()),
                ('patient_datebirth', models.DateField()),
                ('patient_cancer', models.BooleanField(default=False)),
                ('patient_leftcotas', models.IntegerField()),
                ('patient_address', models.CharField(max_length=200)),
                ('patient_phone', models.IntegerField()),
                ('patient_pic', models.BinaryField()),
                ('patient_willaya', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('speciality_id', models.AutoField(primary_key=True, serialize=False)),
                ('speciality_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'speciality',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_role_id', models.IntegerField(blank=True, null=True)),
                ('user_role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('admin', 'Admin')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('apointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('apointment_date', models.DateTimeField()),
                ('apointment_urgent', models.BooleanField(default=False)),
                ('apointment_status', models.BooleanField(default=False)),
                ('apointment_comment', models.CharField(max_length=1000)),
                ('apointment_doc', models.ForeignKey(db_column='apointment_doc', on_delete=django.db.models.deletion.CASCADE, to='sharedapp.doctor')),
                ('apointment_pat', models.ForeignKey(db_column='apointment_pat', on_delete=django.db.models.deletion.CASCADE, to='sharedapp.patient')),
            ],
            options={
                'db_table': 'apointment',
            },
        ),
        migrations.CreateModel(
            name='MessageDoc',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_title', models.CharField(max_length=100)),
                ('message_urgent', models.BooleanField(default=False)),
                ('message_text', models.CharField(max_length=1000)),
                ('message_status', models.BooleanField(default=False)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('message_sender', models.ForeignKey(db_column='message_sender', on_delete=django.db.models.deletion.CASCADE, to='sharedapp.doctor')),
            ],
            options={
                'db_table': 'messagedoc',
            },
        ),
        migrations.CreateModel(
            name='Ordonance',
            fields=[
                ('ordonance_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordonance_file', models.BinaryField()),
                ('ordonance_description', models.CharField(max_length=500)),
                ('ordonance_apointment', models.ForeignKey(db_column='ordonance_apointment', on_delete=django.db.models.deletion.CASCADE, to='sharedapp.appointment')),
            ],
            options={
                'db_table': 'ordonance',
            },
        ),
        migrations.CreateModel(
            name='MessagePat',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_title', models.CharField(max_length=100)),
                ('message_urgent', models.BooleanField(default=False)),
                ('message_text', models.CharField(max_length=1000)),
                ('message_status', models.BooleanField(default=False)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('message_pic', models.BinaryField(blank=True, null=True)),
                ('message_sender', models.ForeignKey(db_column='message_sender', on_delete=django.db.models.deletion.CASCADE, to='sharedapp.patient')),
            ],
            options={
                'db_table': 'messagpat',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('service_duration', models.TimeField()),
                ('service_price', models.IntegerField()),
                ('service_description', models.CharField(max_length=500)),
                ('doc', models.ForeignKey(db_column='doc_id', on_delete=django.db.models.deletion.CASCADE, to='sharedapp.doctor')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='apointment_service',
            field=models.ForeignKey(db_column='apointment_service', on_delete=django.db.models.deletion.CASCADE, to='sharedapp.service'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_speciality',
            field=models.ForeignKey(db_column='doctor_speciality_id', on_delete=django.db.models.deletion.CASCADE, to='sharedapp.speciality'),
        ),
    ]
